version: "3.7"

services:
  notebook:
    image: jupyter/scipy-notebook
    ports:
      - "8080:8888"
    environment:
      GEN_CERT: "yes"
    volumes:
      - scipy-vol:/home/jovyan/work
  data:
    image: kaveh8000/scipy-vol
    volumes:
      - scipy-vol:/data
volumes:
  scipy-vol:
    external: true
    name: scipy-vol
